config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get 'register' => 'account#register_get'

  post 'register' => 'account#register_post'

  get 'people' => 'default#people'

  post 'logout' => 'account#logout'

  post 'login' => 'account#login'

  get 'event/edit' => 'default#edit_event'

  post 'event/edit' => 'default#save_event'

  get 'event/view' => 'default#view_event'

  get 'event/category' => 'default#view_category'

  post 'event/join' => 'default#join_event'
  post 'event/leave' => 'default#leave_event'
  get 'event/attendees' => 'default#get_attendees'

end

app/controllers/default_controller.rb
class DefaultController < ApplicationController

	def people
		user_id = params[:id]
		user = User.where(id: user_id).first
		if user.present?
			@person = {
				id: user.id,
				firstname: user.firstname,
				lastname: user.lastname,
				username: user.username,
				photo: request.protocol + request.host_with_port + "/" + user.photo
			}
			render :layout => "application_alternate"
		else
			redirect_to action: "index", controller: "application"
		end
	end

	def edit_event
		user = nil
		if session[:user_id].present?
			user = User.where(id: session[:user_id]).first
		end
		if user.present?
			event_id = params[:ei]
			@categories = []
			Category.all.to_a.each do |category|
				@categories.push({
					id: category.id,
					name: category.name
				})
			end
			if event_id.present?
				event = Event.where(id: event_id).first
				if event.present?
					if event.user_id == session[:user_id]
						@event = {
							id: event.id,
							title: event.title,
							description: event.description,
							date: event.edate,
							hour: Event.where(id: event.id).pluck("hour(etime)").first.to_i(),
							minute: Event.where(id: event.id).pluck("minute(etime)").first.to_i(),
							lat: event.lat,
							lng: event.lng,
							ampm: event.ampm,
							address: event.address,
							category: event.category.id
						}
						if event.photo.present?
							@event[:photo] = request.protocol + request.host_with_port + "/" + event.photo
						end
						render :layout => "application_alternate"
					else
						redirect_to root_path
					end
				else
					redirect_to root_path
				end
			else
				@event = {
					id: -1,
					lat: -1,
					lng: -1
				}
				render :layout => "application_alternate"
			end
		else
			redirect_to root_path 
		end
	end

	def save_event
		event = nil
		if params[:event_id].to_i() == -1
			event = Event.create_event(session[:user_id], params[:event_title], params[:event_description], 
				params[:event_date], params[:event_time_hour].to_s() + ":" + params[:event_time_minute] + ":00",
				params[:event_address], params[:map_lat], params[:map_lng], params[:event_photo], params[:event_ampm], params[:event_category])	
		else
			event = Event.update_event(session[:user_id], params[:event_id], params[:event_title], params[:event_description], 
				params[:event_date], params[:event_time_hour].to_s() + ":" + params[:event_time_minute] + ":00",
				params[:event_address], params[:map_lat], params[:map_lng], params[:event_photo], params[:event_ampm], params[:event_category])	
		end
		render :json => { status: 0, id: event.id , redirectto: request.protocol + request.host_with_port + "/event/view?ei=" + event.id.to_s()}
	end

	def view_event
		event = nil
		event_id = params[:ei]
		if event_id.present?
			event = Event.where(id: event_id).first
		end
		if event.present?
			user = User.where(id: event.user_id).first
			hour = Event.where(id: event_id).pluck("HOUR(etime)").first.to_s()
			minute = Event.where(id: event_id).pluck("MINUTE(etime)").first.to_s()
			ampm = "AM"
			if minute.to_i() < 10
				minute = "0" + minute
			end
			if hour.to_i() < 10
				hour = "0" + hour
			end
			if event.ampm == 2
				ampm = "PM"
			end
			@event = {
				id: event.id,
				title: event.title,
				description: event.description,
				date: event.edate,
				time: hour + ":" + minute + " " + ampm,
				address: event.address,
				lat: event.lat,
				lng: event.lng,
				category: event.category.name,
				host: {
					id: user.id,
					name: user.firstname + " " + user.lastname,
					username: user.username
				},
				joining: false
			}
			if event.photo.present?
				@event[:photo] = request.protocol + request.host_with_port + "/" + event.photo
			end
			if user.photo.present?
				@event[:host][:photo] = request.protocol + request.host_with_port + "/" + user.photo
			end
			@attendees = [] 
			event_attendees = EventAttendee.where(event_id: event.id)
			if session[:user_id].present?
				@event[:joining] = EventAttendee.where(event_id: event.id, user_id: session[:user_id]).first.present?
				event_attendees = event_attendees.where.not(user_id: session[:user_id])
			end
			event_attendees.take(4).each do |attendee|
				curAttendee = {
					link: request.protocol + request.host_with_port + "/people?id=" + attendee.user_id.to_s()
				}
				photo = User.all.select(:photo).where(id: attendee.user_id).first.photo
				if photo.present?
					curAttendee[:photo] = request.protocol + request.host_with_port + "/" + photo
				end
				@attendees.push(curAttendee)
			end
			render  :layout => "application_alternate"
		else 
			redirect_to root_path
		end
	end

	def view_category
		c = params[:c]
		category = Category.where(name: c).first
		@category = {
			id: category.id,
	        name: category.name,
	        photo: ActionController::Base.helpers.asset_path(category.name + ".jpg"),
	        link:  request.protocol + request.host_with_port+ "/event/category?c=" + category.name,
	        events: []
		}
		Event.where(category_id: category.id).all.to_a.each do |event|
			currentEvent = {
	          id: event.id,
	          title: event.title,
	          description: event.description,
	          author: event.user.firstname + " " + event.user.lastname,
	          link: request.protocol + request.host_with_port + "/event/view?ei=" + event.id.to_s()
	        }
	        if event.photo.present? 
	          currentEvent[:photo] = request.protocol + request.host_with_port + "/" + event.photo
	        end
	        @category[:events].push(currentEvent)
		end
	end

	def join_event
		event_id = params[:event_id]
		user_id = session[:user_id]
		if user_id.present?
			if !EventAttendee.where(event_id: event_id, user_id: user_id).first.present?
				EventAttendee.create(event_id: event_id, user_id: user_id)
				render :json => { status: 0 }
			else
				render :json => { status: 1 }
			end
		else
			render :json => { status: 2 }
		end
	end

	def leave_event
		event_id = params[:event_id]
		user_id = session[:user_id]
		if user_id.present?
			if EventAttendee.where(event_id: event_id, user_id: user_id).first.present?
				EventAttendee.where(event_id: event_id, user_id: user_id).first.destroy
				render :json => { status: 0 }
			else
				render :json => { status: 1 }
			end
		else
			render :json => { status: 2 }
		end
	end

	def get_attendees
		event_id = params[:event_id]
		if event_id.present?
			user_ids = EventAttendee.where(event_id: event_id).pluck(:user_id)
			attendees = []
			User.where("id in (?)", user_ids).to_a.each do |attendee|
				curAttendee = {
					id: attendee.id,
					name: attendee.firstname + " " + attendee.lastname
				}
				if attendee.photo.present?
					curAttendee[:photo] = request.protocol + request.host_with_port + "/" + attendee.photo
				end
				attendees.push(curAttendee)
			end
			render :json => {status: 0, attendees: attendees}
		else
			render :json => {status: 1}
		end
	end
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/views/default/edit_event.html.erb
<% if @event[:id] == -1 %>
	<% content_for :title, "Create event" %>	
<% else %>
	<% content_for :title, "Edit event" %>
<% end %>
<div id="picture" class="z-depth-1" style="height: 400px; padding-top:64px; background-image: url('<%= asset_path('background1.jpg') %>'); background-repeat: no-repeat; background-size: cover; background-attachment:fixed;">
	<div class="container white-text">
		<div class="section">
			<div class="row right-align">
				<a href="#" id="choose-photo" class="btn">Choose Photo</a>
			</div>
		</div>
	</div>
</div>
<div class="section">
	<div class="container">
		<%= form_tag(event_edit_path, method: "post", id: "event-form") do %>
		<div class="section">
			<div class="row">
				<div class="col s4 m3 l2">
					<img class="circle" src="<%= @user[:photo] %>" style="width: 125px; height: 125px;"/>
				</div>
				<div class="col s8 m9 l10" style="padding-top:20px;">
					<h4 style="font-weight: bold;"><%= @user[:name] %></h4>
					<h5>@<%= @user[:username] %></h5>
				</div>
			</div>
		</div>
		<div class="section">
			<p style="font-weight: bold; text-transform:uppercase;">Event title</p>
			<input id="event_title" name="event_title" type="text" placeholder="What should the event be called?" value="<%= @event[:title] %>"></input>
			<p style="font-weight: bold; text-transform:uppercase;">Event description</p>
			<textarea id="event_description" name="event_description" class="materialize-textarea" placeholder="Say something about the event.."><%= @event[:description] %></textarea>
		</div>
		<div class="section">
			<p style="font-weight: bold; text-transform:uppercase;">Event details</p>
			<div class="row">
				<div class="input-field col s6 l4">
					<i class="mdi-action-today prefix"></i> 
					<input id="event_date" name="event_date" type="date" class="datepicker" value="<%= @event[:date] %>"> 
				</div>
				<div class="col s6 l4">
					<div class="col s3 valign-wrapper input-field">
						<div>
						<i class="mdi-device-access-time small"></i>
						</div>
					</div>
					<div class="col s3 input-field">
						<input id="event_time_hour" name="event_time_hour" type="number" min="1" max="12" placeholder="Hour" value="<%= @event[:hour] %>"> 
					</div>
					<div class="col s3 input-field">
						<input id="event_time_minute" name="event_time_minute" type="number" min="0" max="59" placeholder="Minute" value="<%= @event[:minute] %>"> 
					</div>
					<div class="col s3">
						<select id="event_ampm" name="event_ampm" class="material_select">
							<option value="1">AM</option>
							<option value="2">PM</option>
						</select>
					</div>
				</div>
				<div class="col s1 valign-wrapper input-field">
					<div>
						<i class="mdi-maps-local-offer small"></i>
					</div>
				</div>
				<div class="col s11 l3">
					<select id="event_category" name="event_category" class="material_select">
						<% @categories.each do |category| %>
							<option value="<%= category[:id] %>"><%= category[:name] %></option>
						<% end %>
					</select>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12">
					<i class="mdi-maps-place prefix"></i> 
					<input id="event_address" name="event_address" type="text" placeholder="Event address" value="<%= @event[:address] %>"> 
				</div>
			</div>
		</div>
		<input id="map_lat" name="map_lat" type="hidden" value="<%= @event[:lat] %>"/>
		<input id="map_lng" name="map_lng" type="hidden" value="<%= @event[:lng] %>"/>
		<input id="event_photo" name="event_photo" type="file" class="no-display" accept="image/*"/>
		<input id="event_id" name="event_id" type="hidden" value="-1"/>
		<input type="submit" class="no-display"/>
		<% end %>
	</div>
</div>
<div class="section">
	<div class="container">
		<p style="font-weight: bold; text-transform:uppercase;">Event location</p>
	</div>
	<div class="row z-depth-1" style="height: 500px;">
		<div id="map-canvas" style="width:100%;height:100%;"></div>
	</div>
</div>
<div class="container">
	<div class="row right-align">
		<a href="#" class="btn" onclick="$('#event-form').submit();">Post event <i class="mdi-navigation-check right"></i></a>
	</div>	
</div>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>
var currentPoint;
function placeMarker(location) {
	if(typeof currentPoint !== "undefined")
		currentPoint.setMap(null);
	  var marker = new google.maps.Marker({
	    position: location,
	    map: map,
	  });
	  currentPoint = marker;
	  $("#map_lat").val(location.lat())
	  $("#map_lng").val(location.lng());
}

function previewImage(input) {
    if (input.files && input.files[0]) {
    	var reader = new FileReader();
        reader.onload = function (e) {
        	$('#picture').css('background-image', "url('" + e.target.result + "')");
        }
    	reader.readAsDataURL(input.files[0]);
	}
}

$(document).ready(function(){

	<% if @event[:id] > -1 %>
		$("#event_id").val("<%= @event[:id] %>");
		$("#picture").css("background-image", "url('<%= @event[:photo] %>')");
		$("#event_ampm option:nth-child(<%= @event[:ampm] %>)").attr("selected", "true");
		$("#event_category option:nth-child(<%= @event[:category] %>)").attr("selected", "true");
	<% end %>

	$("#choose-photo").click(function(){
		$("#event_photo").click();
	});
	$("#event_photo").change(function(){
		previewImage(this);
	});
    $('.modal-trigger').leanModal();
    $('.collapsible').collapsible({
	    accordion : false
	});
	$("#event_ampm, #event_category").material_select();
    $("#action-join").click(function(){
    	if($(this).hasClass("grey")){
    		$(this).removeClass("grey lighten-3").addClass("green").find("i").removeClass("grey-text").addClass("white-text");
    	} else $(this).removeClass("green").addClass("grey lighten-3").find("i").removeClass("white-text").addClass("grey-text");
    });
    $(".tooltipped").tooltip({
    	delay: 50
    });
    if(google.maps){
    	var latlng = new google.maps.LatLng(14.5746745, 120.9890185);
	    var mapOptions = {
	        zoom: 15,
	        center: latlng,
	        mapTypeId: 'roadmap'
	    }
	    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
	    google.maps.event.addListener(map, 'click', function(event) {
			  placeMarker(event.latLng);
		});

	    if($("#map_lat").val() != -1){
	    	var eventLocation = new google.maps.LatLng($("#map_lat").val(), $("#map_lng").val());
	    	placeMarker(eventLocation);
	    	map.setCenter(eventLocation);
	    }
    } else alert("Google maps failed to load successfully");
	$("#event-form").validate({
		errorClass: "invalid",
		validClass: "valid",
		debug: true,
		errorElement: "span",
		rules:{
			event_title: "required",
			event_time_hour: "required",
			event_time_minute: "required",
			event_date: "required",
			event_address: "required"
		},
		messages: {
			event_title: "You must provide a title for the event",
			event_time_hour: "You must provide the hour for the event",
			event_time_minute: "You must provide the minute for the event",
			event_date: "You must provide the date for the event",
			event_address: "You must provide the address for the event"
		},
		submitHandler: function(form){
			console.log($(form).serialize());
			$.ajax({
				url: $(form).attr("action"),
				data: new FormData(form),
				processData: false,
				contentType: false,
				dataType: "json",
				type: "post",
				success: function(data, textStatus, jqXHR){
					if(data.status == 0){
						location.assign(data.redirectto);
					}
				},
				error: function(jqXHR, textStatus, errorThrown){
					console.log(textStatus);
					toast("An unknown problem was encountered while trying to post the event", 5000, "orange");
				},
				complete: function(){
				}
			});
		}
	});
});
</script>

app/views/default/people.html.erb
<%= content_for :title, @person[:firstname] + " " + @person[:lastname] %>
<!-- Edit modal-->
<div id="edit-modal" class="modal">
	<div class="modal-content">
		<h5>Edit Details</h5>
		<div class="divider"></div>
		<div class="row">
			<div class="input-field col s12">
				<input id="username" type="text" class="validate"> <label
					for="username">Name</label>
			</div>

			<div class="input-field col s12">
				<input id="password" type="text" class="validate"> <label
					for="password">Description</label>
			</div>
			<div class="divider"></div>

			<div class="col s12">
				<div class="progress">
					<div class="determinate" style="width: 70%"></div>
				</div>
			</div>
		</div>
		<a href="#"
			class="waves-effect waves-dark amber darken-1 btn modal-action modal-close right">Apply</a>
	</div>
</div>
<div class="section"></div>
<div class="container">
	<div class="row">
		<div class="col s12 m12 l12">
			<div class="card-panel" style="padding-left: 50px; padding-right: 50px;">
				<div class="row">
					<div class="col s12 m4 l3">
						<img id="profile-avatar" src="<%= @person[:photo] %>" alt="" class="circle">
					</div>
					<div id="profile-name" class="col s12 m6 l9">
						<h5 style="font-weight: bold;"><%= @person[:firstname] + " " + @person[:lastname] %></h5>
						<span>@<%= @person[:username] %></span>
					</div>
				</div>
				<!--
				<% if @user.present? && @user[:id] == @person[:id] %>
					<div class="row">
						<div class="col s12">
							<a
								class="waves-effect waves-light btn modal-trigger right amber darken-1"
								href="#edit-modal">Edit&nbsp;Profile<i
								class="mdi-editor-mode-edit right"></i></a>
						</div>
					</div>
				<% end %>
				-->
				<div class="divider"></div>
<!--
				<div class="section">
					<div class="row">
						<div class="col s12">
							<ul class="tabs">
								<li class="tab col s6"><a href="#test1">Created
										Events</a></li>
								<li class="tab col s6"><a class="active"
									href="#test2">Joined Events</a></li>
							</ul>
						</div>
						<div id="test1" class="col s12">
							<ul class="collapsible" data-collapsible="accordion">
								<li>
									<div class="collapsible-header">
										<i class="mdi-image-filter-drama"></i>Event Names
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
								<li>
									<div class="collapsible-header">
										<i class="mdi-maps-place"></i>Event Name
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
								<li>
									<div class="collapsible-header">
										<i class="mdi-social-whatshot"></i>Event Name
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
							</ul>

						</div>
						<div id="test2" class="col s12">
							<ul class="collapsible" data-collapsible="accordion">
								<li>
									<div class="collapsible-header">
										<i class="mdi-image-filter-drama"></i>Event Names
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
								<li>
									<div class="collapsible-header">
										<i class="mdi-maps-place"></i>Event Name
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
								<li>
									<div class="collapsible-header">
										<i class="mdi-social-whatshot"></i>Event Name
									</div>
									<div class="collapsible-body">
										<p>Lorem ipsum dolor sit amet.</p>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			-->
			</div>
		</div>
	</div>
	<div class="col s8 m8 l8">
		</div>

		<div class="section"></div>
		<div class="divider"></div>
	</div>
</div>
<script>
  $(document).ready(function(){
    $('.modal-trigger').leanModal();
  });

  $(document).ready(function(){
    $('.collapsible').collapsible({
      accordion : false
    });
  });
</script>

app/views/default/view_category.html.erb
<% content_for :title, @category[:name] %>
<div  style="background-image: url('<%= @category[:photo] %>'); background-size: cover; background-attachment: fixed; height: 350px; width: 100%;">
	<div class="container">
		<h1 style="font-size: 15rem; line-height: 350px; margin-top: 0; color: rgba(0,0,0,0.5);"><%= @category[:name] %></h1>
	</div>
</div>
<div class="container">
	<div class="section">
		<div class="row" style="min-height: 500px;">
		<% if @category[:events].size > 0 %>
			<% @category[:events].each do |event| %>
				<div class="col l4 m6 s12">
					<div class="card medium">
				        <div class="card-image waves-effect waves-block waves-light">
				          <img class="activator" src="<%= event[:photo] %>">
				        </div>
				        <div class="card-content">
				          <span class="card-title grey-text text-darken-4"><a target="_blank" style="text-transform: none;" href="<%= event[:link] %>" class="grey-text text-darken-4"><%= event[:title] %></a><i style="cursor: pointer" class="activator mdi-navigation-more-vert right"></i></span>
				        </div>
				        <div class="card-reveal">
				          <span class="card-title grey-text text-darken-4"><%= event[:title] %> <i class="mdi-navigation-close right"></i></span>
				          <p><%= event[:description] %></p>
				        </div>
				    </div>
				</div>
			<% end %>
		<% else %>
			<div class="valign-wrapper" style="width: 100%; height: 500px;">
				<h3 class="center-align grey-text text-lighten-1" style="width: 100%;">There are no events yet</h3>
			</div>
		<% end %>
		</div>
	</div>
</div>